### PR TITLE
Header Component changes

### PR DESCRIPTION
**Pull request by anuradha9712**
image

### CODE REVIEW

**Comment by AkbarHabeeb** [comment]
Can u resolve those conflicts @anuradha9712

**Review by vsasvipul0605 — APPROVED** [review]

**Review by vsasvipul0605 — APPROVED** [review]
First _git pull_ and then add your files and then raise PR. I think conflicts will be resolved then.

**Comment by anuradha9712** [comment]
I have already followed the same steps twice but I don't why there is always a conflict

**Comment by AkbarHabeeb** [comment]
@anuradha9712 Pull the dev branch and then do your changes in it. It seems you have been pulling the master one.

**Comment by AkbarHabeeb** [comment]
Redundant of #16

**Pull request closed without merging**
